services:
  mysql:
    container_name: 'mysql-notificacao-ms'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=notificacaodb'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD=123'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'